Opt("WinTitleMatchMode", 2)
WinWait ( $CmdLine[1])
WinActivate ( $CmdLine[1])
WinWaitActive ( $CmdLine[1])
; WinWaitActive ( $CmdLine[1] )
ControlSetText ( $CmdLine[1] , "" , $CmdLine[2]  , $CmdLine[3] )
